server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root@csu
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: true
